---
- name: Set branch name
  ansible.builtin.set_fact:
    branch_name: "topo_update_{{ now(fmt='%m%d_%H%M%S') }}"

- name: Set Git remote URL with token
  shell: git remote set-url origin https://{{ github_token }}@github.com/GomathiselviS/myutilities.git
  args:
    chdir: /path/to/your/repo
  environment:
    GIT_TERMINAL_PROMPT: 0
  register: remote_result
  failed_when: remote_result.rc != 0

- name: Create a Git branch
  ansible.builtin.command:
    cmd: "git checkout -b {{ branch_name }}"

- name: Push branch
  ansible.builtin.command:
    cmd: "git push origin {{ branch_name }}"

- name: Scaffold topology
  ansible.builtin.include_tasks: render_topology.yaml
  loop: "{{ topology }}"
  loop_control:
    loop_var: topology_item

- name: Add files to the branch
  ansible.builtin.command:
    cmd: "git add ."

- name: Commit the changes
  ansible.builtin.command:
    cmd: "git -c user.name={{ github_user }} -c user.email={{ github_email }} commit -m ' Add Topology Documentation '"

- name: Create a Pull Request
  uri:
    url: https://api.github.com/repos/GomathiselviS/myutilities/pulls
    method: POST
    headers:
      Authorization: "Bearer {{ github_token }}"
      Accept: "application/vnd.github+json"
      Content-Type: "application/json"
    body: |
      {
        "title": "Add Topology Document",
        "head": "{{ branch_name }}",
        "base": "main",
        "body": "This PR is created by GitHub Workflow. It scaffolds topology documentation file. "
      }
    body_format: json
    return_content: yes
  register: result

- debug:
    msg: "PR created successfully with URL: {{ result.json.html_url }}"
  when: result.status == 201
