name: Create PR

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
 
    - name: Set playbook filename variable
      id: set_playbook_filename
      run: |
        echo "::set-output name=playbook_filename::tools/generate_aap_cicd_topology_doc/generate_markdown.yaml"

    - name: Run Ansible Role to Create PR
      run: |
        ansible-playbook -i "localhost" "${{ steps.set_playbook_filename.outputs.playbook_filename }}"
      env:
        GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
