name: Create PR

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'GitHub Token'
        required: true
      github_user:
        description: 'GitHub User Name'
        required: true
      github_email:
        description: 'GitHub User Email'
        required: true
      topology_info:
        description: |
          For more information, see the [topolofy info file](https://github.com/GomathiselviS/myutilities/blob/main/tools/generate_aap_cicd_topology_doc/files/info.yaml).
        required: true

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ansible
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
 
    - name: Set playbook filename variable
      id: set_playbook_filename
      run: |
        echo "::set-output name=playbook_filename::tools/generate_aap_cicd_topology_doc/generate_markdown.yaml"

    - name: Run Ansible Role to Create PR
      run: |
        ansible-playbook -i "localhost" "${{ steps.set_playbook_filename.outputs.playbook_filename }}" -e "topology_info='${{ github.event.inputs.topology_info}}' github_token='${{ github.event.inputs.github_token }}' github_user='${{ github.event.inputs.github_user }}' github_email='${{ github.event.inputs.github_email }}'" -vvv
      env:
        GIT_USER_NAME: ${{ github.event.inputs.github_user }}
        GIT_USER_EMAIL: ${{ github.event.inputs.github_email }}
        GITHUB_TOKEN: ${{ github.event.inputs.github_token }}
